"""add_content_hash

Revision ID: 1690cfde70ef
Revises: 306057086411
Create Date: 2025-12-21 01:25:03.757225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1690cfde70ef'
down_revision: Union[str, Sequence[str], None] = '306057086411'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('content_hash', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_messages_content_hash'), 'messages', ['content_hash'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_messages_content_hash'), table_name='messages')
    op.drop_column('messages', 'content_hash')
    # ### end Alembic commands ###
