"""init

Revision ID: 365595ae6af5
Revises:
Create Date: 2025-11-30 12:50:59.539606

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "365595ae6af5"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
  """Upgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.create_table(
    "messages",
    sa.Column("id", sa.String(), nullable=False),
    sa.Column("external_id", sa.String(), nullable=False),
    sa.Column("created_at", sa.DateTime(), nullable=False),
    sa.Column("event_date", sa.DateTime(), nullable=False),
    sa.Column("source", sa.String(), nullable=False),
    sa.Column("user_id", sa.String(), nullable=False),
    sa.Column("text", sa.String(), nullable=False),
    sa.Column("cleaned_text", sa.String(), nullable=False),
    sa.Column("lang_code", sa.String(), nullable=False),
    sa.Column("lang_score", sa.Float(), nullable=False),
    sa.Column(
      "sentiment_label",
      sa.Enum("POSITIVE", "NEGATIVE", "NEUTRAL", name="sentiment_enum"),
      nullable=False,
    ),
    sa.Column("sentiment_score", sa.Float(), nullable=False),
    sa.Column(
      "emotion_label",
      sa.Enum(
        "ANGER",
        "AVERAGE",
        "FEAR",
        "DISGUST",
        "JOY",
        "SADNESS",
        "SURPRISE",
        "GUILT",
        "INTEREST",
        "NEUTRAL",
        name="emotion_enum",
      ),
      nullable=False,
    ),
    sa.Column("emotion_score", sa.Float(), nullable=False),
    sa.Column(
      "category_level_1",
      sa.Enum(
        "BEFORE_FLIGHT",
        "DEPARTURE_ARRIVAL",
        "ON_BOARD",
        "AFTER_FLIGHT",
        "LOYALTY_SALES",
        "TECHNICAL_ISSUES",
        "FEEDBACK",
        "SERVICE",
        "OTHER",
        name="category_level_1_enum",
      ),
      nullable=False,
    ),
    sa.Column(
      "category_level_2",
      postgresql.ARRAY(
        sa.Enum(
          "BOOKING",
          "PAYMENT",
          "REGISTRATION",
          "BAGGAGE_BEFORE_FLIGHT",
          "DOCUMENTS",
          "FLIGHT_STATUS",
          "FLIGHT_DELAY",
          "FLIGHT_CANCELLATION",
          "HOTEL_TRANSFER",
          "BAGGAGE_SEARCH",
          "CABIN_SERVICE",
          "CABIN_CLEANLINESS",
          "CABIN_COMFORT",
          "CABIN_FOOD",
          "CABIN_ENTERTAINMENT",
          "CABIN_BAGGAGE",
          "TICKET_REFUND",
          "TICKET_EXCHANGE",
          "COMPENSATION",
          "LOST_PROPERTY",
          "LOYALTY_PROGRAM",
          "PROMOTIONS_FARES",
          "WEBSITE_APP_ISSUES",
          "BOT_ISSUES",
          "COMPLAINT",
          "THANK_YOU",
          "SUGGESTION",
          "ESCALATION",
          "GREETING",
          "FAREWELL",
          "OTHER",
          name="category_level_2_enum",
        )
      ),
      nullable=False,
    ),
    sa.PrimaryKeyConstraint("id"),
  )
  op.create_index(
    "ix_messages_cat_level_2",
    "messages",
    ["category_level_2"],
    unique=False,
    postgresql_using="gin",
  )
  op.create_index(
    op.f("ix_messages_category_level_1"),
    "messages",
    ["category_level_1"],
    unique=False,
  )
  op.create_index(
    "ix_messages_content_search",
    "messages",
    [sa.literal_column("to_tsvector('simple', cleaned_text)")],
    unique=False,
    postgresql_using="gin",
  )
  op.create_index(op.f("ix_messages_emotion_label"), "messages", ["emotion_label"], unique=False)
  op.create_index(op.f("ix_messages_event_date"), "messages", ["event_date"], unique=False)
  op.create_index(op.f("ix_messages_external_id"), "messages", ["external_id"], unique=False)
  op.create_index(op.f("ix_messages_lang_code"), "messages", ["lang_code"], unique=False)
  op.create_index(
    op.f("ix_messages_sentiment_label"),
    "messages",
    ["sentiment_label"],
    unique=False,
  )
  op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
  # ### end Alembic commands ###


def downgrade() -> None:
  """Downgrade schema."""
  # ### commands auto generated by Alembic - please adjust! ###
  op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
  op.drop_index(op.f("ix_messages_sentiment_label"), table_name="messages")
  op.drop_index(op.f("ix_messages_lang_code"), table_name="messages")
  op.drop_index(op.f("ix_messages_external_id"), table_name="messages")
  op.drop_index(op.f("ix_messages_event_date"), table_name="messages")
  op.drop_index(op.f("ix_messages_emotion_label"), table_name="messages")
  op.drop_index("ix_messages_content_search", table_name="messages", postgresql_using="gin")
  op.drop_index(op.f("ix_messages_category_level_1"), table_name="messages")
  op.drop_index("ix_messages_cat_level_2", table_name="messages", postgresql_using="gin")
  op.drop_table("messages")
  # ### end Alembic commands ###
